RUN_MODE = "RASPBERRY"  # Options: "SIMULATION", "RASPBERRY"

# Raspberry GPIO / Grove pins
CAMERA_PORT = "CSI"

PIR_PIN = 16
BUZZER_PIN = 18

# Sound sensor via ADC
SOUND_CHANNEL = 0

# Thresholds
SOUND_THRESHOLD = 600

# Emergency timing
FALL_CONFIRMATION_SECONDS = 20
USER_RESPONSE_SECONDS = 20